theme: jekyll-theme-chirpy   # keep this
lang: en
timezone: Asia/Manila

title: "Xine003"
tagline: "It might take some time"
description: "All Xine003's CTF writeups are here!"

url: "http://localhost:4000"
baseurl: ""

github:
  username: Xine003

social:
  name: Xine003
  email: xine003@proton.me
  links:
    - https://github.com/Xine003
    - https://www.linkedin.com/in/franxine-orias/

paginate: 10   # posts per page
